package com.paymentgateway.payout.cashfreePayout;

public class Constants {
	
		public static final String ADF_1 = "ADF_1";
		public static final String ADF_2 = "ADF_2";
		public static final String ADF_3 = "ADF_3";
		public static final String ADF_4 = "ADF_4";
		public static final String ADF_5 = "ADF_5";
		public static final String ADF_6 = "ADF_6";
		public static final String ADF_7 = "ADF_7";
		public static final String ADF_8 = "ADF_8";
		public static final String ADF_9 = "ADF_9";
		public static final String ADF_10 = "ADF_10";
		public static final String ADF_11 = "ADF_11";
		public static final String ADF_12 = "ADF_12";
		public static final String ADF_13 = "ADF_13";
		public static final String ADF_14 = "ADF_14";
		public static final String ADF_15 = "ADF_15";
		public static final String ADF_16 = "ADF_16";
		public static final String ADF_17 = "ADF_17";
		public static final String ADF_18 = "ADF_18";
		public static final String ADF_19 = "ADF_19";
		public static final String ADF_20 = "ADF_20";
		public static final String ADF_21 = "ADF_21";
		public static final String ADF_22 = "ADF_22";
		public static final String ADF_23 = "ADF_23";
		public static final String ADF_24 = "ADF_24";
		public static final String ADF_25 = "ADF_25";
		public static final String ADF_26 = "ADF_26";
		public static final String ADF_27 = "ADF_27";
		public static final String ADF_28 = "ADF_28";
		public static final String ADF_29 = "ADF_29";
		public static final String ADF_30 = "ADF_30";
		public static final String ADF_31 = "ADF_31";
		public static final String ADF_32 = "ADF_32";
		public static final String ADF_33 = "ADF_33";
		public static final String ADF_34 = "ADF_34";
		public static final String ADF_35 = "ADF_35";
		public static final String ADF_36 = "ADF_36";
		public static final String ADF_37 = "ADF_37";
		public static final String ADF_38 = "ADF_38";
		public static final String ADF_39 = "ADF_39";
		public static final String ADF_40 = "ADF_40";
		public static final String ADF_41 = "ADF_41";
		public static final String ADF_42 = "ADF_42";
		public static final String ADF_43 = "ADF_43";
		public static final String ADF_44 = "ADF_44";
		public static final String ADF_45 = "ADF_45";
		public static final String ADF_46 = "ADF_46";
		public static final String ADF_47 = "ADF_47";
		public static final String ADF_48 = "ADF_48";
		public static final String ADF_49 = "ADF_49";
		public static final String ADF_50 = "ADF_50";
}
