export function multilingualText(lang, dataKey) {
    var $multilingualText = {
        english: {
            upiQrText: "(Please scan UPI QR using any UPI App)",
            saveWlText: "Save this wallet for future payments",
            saveNbText: "Save this bank for future payments",
            expiry: "Expiry",
            orderId: "Order ID",
            amount: "Amount",
            convenienceFee: "Convenience Fee",
            amountPayable: "Amount Payable",
            savedCards: "Saved Cards",
            savedVpa: "Saved Vpa",
            savedBanks: "Saved Banks",
            savedWallet: "Saved Wallets",
            card: "Cards",
            creditCard: "Credit Card",
            debitCard: "Debit Card",
            international: "International",
            upi: "UPI",
            upiQr: "Scan &amp; Pay",
            netBanking: "Net Banking",
            wallet: "Wallet",
            paytm: "Paytm",
            cashondelivery: "Cash on Delivery",
            payathotel: "Pay at Hotel",
            payondelivery: "Pay on Delivery",
            emi: "EMI",
            cardNumber: "Card Number",
            checkStartNo: "Invalid Card Number",
            validCardCheck: "Invalid Card Number",
            emptyCardNumber: "Please Enter Card Number",
            notSupportedCard: "Card Not Supported",
            validExpDate: "Invalid Date",
            emptyExpiry: "Please Enter Expiry",
            cvvTitle: "What is CVV?",
            cvvText: "The CVV number is the last three digits on the back of your card",
            btnOk: "Ok",
            cvvValidate: "Invalid CVV",
            emptyCvv: "Please Enter CVV",
            nameOnCard: "Name on Card",
            nameError: "Please Enter Name",
            invalidError: "Invalid Name",
            saveCardCheckboxText: "Save this card for future payments",
            otherBank: "Or select bank from dropdown",
            errorBankList: "Please Select Bank",
            vpaAddress: "UPI ID",
            invalidVpa: "Invalid UPI ID",
            enterVpa: "Please Enter UPI ID",
            vpaPara: "UPI ID is a unique Payment address that is linked to a person's bank account to make payments.",
            vpaName: "Name",
            invalidVpaName: "Invalid Name",
            enterVpaName: "Please Enter Name",
            saveVpaText: "Save this UPI ID for future payments",
            poweredBy: "Powered by:",
            errorWalletList: "Please choose any wallet type",
            errorCOD: "Please choose COD",
            emiValue: "EMI Value",
            emiInterestText: "Interest",
            chargedByBank: "(charged by Bank)",
            totalEmiText: "Total EMI for",
            emiMonthsText: "months",
            cancel: "Cancel",
            payBtnText: "Pay",
            selectBank: "Select Bank",
            selectDebitCredit: "Select Debit/Credit",
            emiBankErrorBefore: "Please enter ",
            emiBankErrorAfter: " Card Number",
            emiCardErrorBefore: "Please enter ",
            emiCardErrorAfter: " number",
            errorCardDomestic: "Please enter Domestic Card number",
            emiFor: "for",
            emiMonths: "months",
            timeExpireTextBefore: "This page will expire in",
            timeExpireTextAfter: "",
            retryHeading: "Payment Failed? Retry Now",
            retryBtn: "Retry",
            returnMerchant: "Return to Merchant",
            upiApprovalText: "Please approve the payment in your UPI App",
            upiStopRefresh: "Do not refresh this page or press back button",
            seeDetails: "See Details",
            hideDetails: "Hide Details",
            defaultLoaderText: "Please wait while we process your payment...",
            summary: "Summary",
            quickPay: "Quick Pay",
            gst: "GST",
            mobileNumber: "Mobile Number",
            useAnotherMobile: "Use another Mobile Number",
            enterOtp: "Enter OTP",
            resendOtp: "Resend OTP",
            availableBalance: "Available Balance",
            refreshBalance: "Check Balance",
            addMoney: "Add money",
            insufficientFund: "Insufficient funds!",
            rechargeWallet: "Please recharge your wallet...",
            useAnotherMobileAlt: "Login using another Mobile Number",
            loggedIn: "You are logged in using",
            loggedInAlt: "",
            payUsingUpi: "PAY USING UPI ID",
            payUsingQr: "PAY USING QR CODE"
        },
        hindi: {
            upiQrText: "(कृपया किसी भी UPI App का उपयोग करके UPI QR को स्कैन करें)",
            saveWlText: "भविष्य के भुगतान के लिए इस वॉलेट को सहेजें",
            saveNbText: "भविष्य के भुगतान के लिए इस बैंक को सहेजें",
            expiry: "समाप्ति",
            orderId: "आदेश कामतत्व",
            amount: "रकम",
            convenienceFee: "सुविधा शुल्क",
            amountPayable: "देय राशि",
            savedCards: "सहेजे गए कार्ड",
            savedVpa: "सहेजे गए VPA",
            savedBanks: "सहेजे गए बैंक",
            savedWallet: "सहेजे गए वॉलेट",
            card: "कार्ड्स",
            creditCard: "क्रेडिट कार्ड",
            debitCard: "डेबिट कार्ड",
            international: "अंतरराष्ट्रीय",
            upi: "यू.पी.आई",
            upiQr: "स्कैन और भुगतान",
            netBanking: "नेट बैंकिंग",
            wallet: "वॉलेट",
            paytm: "पेटीएम",
            cashondelivery: "डिलवरी पर नकदी",
            payathotel: "होटल में भुगतान करें",
            payondelivery: "सामान देने के समय भुगतान",
            emi: "ई.एम.आई.",
            cardNumber: "कार्ड नंबर",
            checkStartNo: "अवैध कार्ड संख्या",
            validCardCheck: "अवैध कार्ड संख्या",
            emptyCardNumber: "कृपया कार्ड नंबर दर्ज करें",
            notSupportedCard: "कार्ड समर्थित नहीं है",
            validExpDate: "अमान्य तिथि",
            emptyExpiry: "कृपया समाप्ति तिथि दर्ज करें",
            cvvTitle: "CVV क्या है?",
            cvvText: "सीवीवी नंबर आपके कार्ड के पीछे तीन अंक हैं",
            btnOk: "ठीक",
            cvvValidate: "अमान्य CVV",
            emptyCvv: "कृपया CVV दर्ज करें",
            nameOnCard: "कार्ड पर नाम",
            nameError: "कृपया नाम दर्ज करें",
            invalidError: "गलत नाम",
            saveCardCheckboxText: "भविष्य के भुगतान के लिए इस कार्ड को सहेजें",
            otherBank: "अन्य बैंक",
            errorBankList: "कृपया बैंक चुनें",
            vpaAddress: "यूपीआई आईडी",
            invalidVpa: "अमान्य VPA",
            enterVpa: "कृपया VPA दर्ज करें",
            vpaPara: "UPI आईडी एक अद्वितीय भुगतान पता है जो भुगतान करने के लिए किसी व्यक्ति के बैंक खाते से जुड़ा होता है।",
            vpaName: "नाम",
            invalidVpaName: "गलत नाम",
            enterVpaName: "कृपया नाम दर्ज करें",
            saveVpaText: "भविष्य के भुगतान के लिए इस VPA को सहेजें",
            poweredBy: "द्वारा संचालित:",
            errorWalletList: "कृपया कोई भी वॉलेट प्रकार चुनें",
            errorCOD: "कृपया 'डिलवरी पर नकदी' चुनें",
            emiValue: "ई.एम.आई. मूल्य",
            emiInterestText: "ब्याज",
            chargedByBank: "(बैंक द्वारा प्रभारित)",
            totalEmiText: "कुल ई.एम.आई.",
            emiMonthsText: "महीनों के लिए",
            cancel: "रद्द करें",
            payBtnText: "अदा करे",
            selectBank: "बैंक का चयन करें",
            selectDebitCredit: "डेबिट/क्रेडिट चुनें",
            emiBankErrorBefore: "कृपया ",
            emiBankErrorAfter: " कार्ड नंबर दर्ज करें",
            emiCardErrorBefore: "कृपया ",
            emiCardErrorAfter: " नंबर दर्ज करें",
            errorCardDomestic: "कृपया डोमेस्टिक कार्ड नंबर दर्ज करें",
            emiFor: ",",
            emiMonths: "महीने के लिए",
            timeExpireTextBefore: "यह पृष्ठ",
            timeExpireTextAfter: "में समाप्त होगा",
            retryHeading: "भुगतान असफल हुआ? अब पुन: प्रयास करें",
            retryBtn: "पुन: प्रयास करें",
            returnMerchant: "मर्चेंट पर वापस जाएँ",
            upiApprovalText: "कृपया अपने UPI App में भुगतान स्वीकृत करें",
            upiStopRefresh: "इस पृष्ठ को रीफ़्रेश न करें या बैक बटन न दबाएँ",
            seeDetails: "विवरण देखें",
            hideDetails: "विवरण छिपाएँ",
            defaultLoaderText: "कृपया प्रतीक्षा करें जब तक हम आपका भुगतान संसाधित करते हैं...",
            summary: "सारांश",
            quickPay: "त्वरित भुगतान",
            gst: "GST",
            mobileNumber: "मोबाइल नंबर",
            useAnotherMobile: "दूसरे मोबाइल नंबर का उपयोग करें",
            enterOtp: "OTP दर्ज करें",
            resendOtp: "OTP पुनः भेजें",
            availableBalance: "उपलब्ध शेष राशि",
            refreshBalance: "बकाया जाँचो",
            addMoney: "पैसे जोड़ें",
            insufficientFund: "अपर्याप्त कोष!",
            rechargeWallet: "कृपया अपना बटुआ रिचार्ज करें ...",
            useAnotherMobileAlt: "दूसरे मोबाइल नंबर का उपयोग करके लॉगिन करें",
            loggedIn: "आप",
            loggedInAlt: "का उपयोग कर लॉगिन हैं",
            payUsingUpi: "UPI आईडी का उपयोग करके भुगतान करें",
            payUsingQr: "क्यूआर कोड का उपयोग करके भुगतान करें"
        },
        punjabi: {
            upiQrText: "(ਕਿਰਪਾ ਕਰਕੇ ਕਿਸੇ ਵੀ ਯੂਪੀਆਈ ਐਪ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਯੂਪੀਆਈ ਕਿ Qਆਰ ਨੂੰ ਸਕੈਨ ਕਰੋ)",
            saveWlText: "ਭਵਿੱਖ ਵਿੱਚ ਭੁਗਤਾਨਾਂ ਲਈ ਇਸ ਵਾਲਿਟ ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰੋ",
            saveNbText: "ਭਵਿੱਖ ਵਿੱਚ ਭੁਗਤਾਨਾਂ ਲਈ ਇਸ ਬੈਂਕ ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰੋ",
            expiry: "ਅੰਤ",
            orderId: "ਆਰਡਰ ਆਈਡੀ",
            amount: "ਰਕਮ",
            convenienceFee: "ਸਹੂਲਤ ਫੀਸ",
            amountPayable: "ਭੁਗਤਾਨ ਯੋਗ ਰਕਮ",
            savedCards: "ਸੁਰੱਖਿਅਤ ਕਾਰਡ",
            savedVpa: "ਸੇਵ ਵੀਪੀਏ",
            savedBanks: "ਸੁਰੱਖਿਅਤ ਬੈਂਕਾਂ",
            savedWallet: "ਸੁਰੱਖਿਅਤ ਵਾਲਿਟ",
            card: "ਕਾਰਡ",
            creditCard: "ਕਰੇਡਿਟ ਕਾਰਡ",
            debitCard: "ਡੈਬਿਟ ਕਾਰਡ",
            international: "ਅੰਤਰਰਾਸ਼ਟਰੀ",
            upi: "ਯੂ.ਪੀ.ਆਈ.",
            upiQr: "ਸਕੈਨ ਅਤੇ ਪੇ",
            netBanking: "ਨੈੱਟ ਬੈਂਕਿੰਗ",
            wallet: "ਵਾਲਿਟ",
            paytm: "ਪੇਟੀਐਮ",
            cashondelivery: "ਡਿਲਿਵਰੀ ਤੇ ਨਕਦ",
            payathotel: "ਹੋਟਲ ਵਿਚ ਭੁਗਤਾਨ ਕਰੋ",
            payondelivery: "ਡਿਲਿਵਰੀ 'ਤੇ ਭੁਗਤਾਨ ਕਰੋ",
            emi: "ਈ.ਐੱਮ.ਆਈ.",
            cardNumber: "ਕਾਰਡ ਨੰਬਰ",
            checkStartNo: "ਗਲਤ ਕਾਰਡ ਨੰਬਰ",
            validCardCheck: "ਗਲਤ ਕਾਰਡ ਨੰਬਰ",
            emptyCardNumber: "ਕਿਰਪਾ ਕਰਕੇ ਕਾਰਡ ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
            notSupportedCard: "ਕਾਰਡ ਸਹਿਯੋਗੀ ਨਹੀਂ ਹੈ",
            validExpDate: "ਅਵੈਧ ਤਾਰੀਖ",
            emptyExpiry: "ਕਿਰਪਾ ਅੰਤ ਦੀ ਮਿਤੀ ਦਾਖਲ ਕਰੋ",
            cvvTitle: "ਸੀਵੀਵੀ ਕੀ ਹੈ?",
            cvvText: "ਤੁਹਾਡੇ ਕਾਰਡ ਦੇ ਪਿਛਲੇ ਪਾਸੇ ਸੀਵੀਵੀ ਨੰਬਰ ਤਿੰਨ ਅੰਕਾਂ ਦਾ ਹੁੰਦਾ ਹੈ",
            btnOk: "ਠੀਕ ਹੈ",
            cvvValidate: "ਅਵੈਧ ਸੀਵੀਵੀ",
            emptyCvv: "ਕਿਰਪਾ ਕਰਕੇ ਸੀਵੀਵੀ ਦਰਜ ਕਰੋ",
            nameOnCard: "ਕਾਰਡ 'ਤੇ ਨਾਮ",
            nameError: "ਕਿਰਪਾ ਕਰਕੇ ਨਾਮ ਦਾਖਲ ਕਰੋ",
            invalidError: "ਗਲਤ ਨਾਮ",
            saveCardCheckboxText: "ਭਵਿੱਖ ਵਿੱਚ ਭੁਗਤਾਨਾਂ ਲਈ ਇਸ ਕਾਰਡ ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰੋ",
            otherBank: "ਹੋਰ ਬੈਂਕ",
            errorBankList: "ਕਿਰਪਾ ਕਰਕੇ ਬੈਂਕ ਦੀ ਚੋਣ ਕਰੋ",
            vpaAddress: "ਵਰਚੁਅਲ ਭੁਗਤਾਨ ਦਾ ਪਤਾ",
            invalidVpa: "ਅਵੈਧ ਵੀਪੀਏ",
            enterVpa: "ਕਿਰਪਾ ਕਰਕੇ ਵੀਪੀਏ ਦਰਜ ਕਰੋ",
            vpaPara: "ਯੂ ਪੀ ਆਈ ਆਈ ਇਕ ਵਿਲੱਖਣ ਭੁਗਤਾਨ ਦਾ ਪਤਾ ਹੈ ਜੋ ਭੁਗਤਾਨ ਕਰਨ ਲਈ ਕਿਸੇ ਵਿਅਕਤੀ ਦੇ ਬੈਂਕ ਖਾਤੇ ਨਾਲ ਜੁੜਿਆ ਹੁੰਦਾ ਹੈ.",
            vpaName: "ਨਾਮ",
            invalidVpaName: "ਗਲਤ ਨਾਮ",
            enterVpaName: "ਕਿਰਪਾ ਕਰਕੇ ਨਾਮ ਦਾਖਲ ਕਰੋ",
            saveVpaText: "ਭਵਿੱਖ ਦੇ ਭੁਗਤਾਨਾਂ ਲਈ ਇਸ VPA ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰੋ",
            poweredBy: "ਦੁਆਰਾ ਸੰਚਾਲਿਤ:",
            errorWalletList: "ਕਿਰਪਾ ਕਰਕੇ ਕਿਸੇ ਵੀ ਵਾਲਿਟ ਦੀ ਕਿਸਮ ਦੀ ਚੋਣ ਕਰੋ",
            errorCOD: "ਕਿਰਪਾ ਕਰਕੇ 'ਡਿਲਿਵਰੀ ਤੇ ਨਕਦ' ਦੀ ਚੋਣ ਕਰੋ",
            emiValue: "ਈ.ਐੱਮ.ਆਈ. ਮੁੱਲ",
            emiInterestText: "ਵਿਆਜ",
            chargedByBank: "(ਬੈਂਕ ਦੁਆਰਾ ਚਾਰਜ ਕੀਤਾ ਗਿਆ)",
            totalEmiText: "",
            emiMonthsText: "ਮਹੀਨਿਆਂ ਲਈ ਕੁੱਲ ਈ.ਐੱਮ.ਆਈ.",
            cancel: "ਰੱਦ ਕਰੋ",
            payBtnText: "ਭੁਗਤਾਨ ਕਰੋ",
            selectBank: "ਬੈਂਕ ਦੀ ਚੋਣ ਕਰੋ",
            selectDebitCredit: "ਡੈਬਿਟ/ਕ੍ਰੈਡਿਟ ਦੀ ਚੋਣ ਕਰੋ",
            emiBankErrorBefore: "ਕਿਰਪਾ ਕਰਕੇ ",
            emiBankErrorAfter: " ਕਾਰਡ ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
            emiCardErrorBefore: "ਕਿਰਪਾ ਕਰਕੇ ",
            emiCardErrorAfter: " ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
            errorCardDomestic: "ਕਿਰਪਾ ਕਰਕੇ ਡੋਮੇਸਟਿਕ ਕਾਰਡ ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
            emiFor: ",",
            emiMonths: "ਮਹੀਨੇ ਲਈ",
            timeExpireTextBefore: "ਇਹ ਪੇਜ",
            timeExpireTextAfter: "ਵਿੱਚ ਖਤਮ ਹੋ ਜਾਵੇਗਾ",
            retryHeading: "ਭੁਗਤਾਨ ਅਸਫਲ? ਹੁਣ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
            retryBtn: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
            returnMerchant: "ਵਪਾਰੀ ਤੇ ਵਾਪਸ ਜਾਓ",
            upiApprovalText: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਯੂਪੀਆਈ ਐਪ ਵਿਚ ਭੁਗਤਾਨ ਨੂੰ ਮਨਜ਼ੂਰੀ ਦਿਓ",
            upiStopRefresh: "ਇਸ ਪੰਨੇ ਨੂੰ ਤਾਜ਼ਾ ਨਾ ਕਰੋ ਜਾਂ ਪਿੱਛੇ ਬਟਨ ਨੂੰ ਦਬਾਓ",
            seeDetails: "ਵੇਰਵੇ ਵੇਖੋ",
            hideDetails: "ਵੇਰਵੇ ਓਹਲੇ",
            defaultLoaderText: "ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ ਜਦੋਂ ਤੱਕ ਅਸੀਂ ਤੁਹਾਡੇ ਭੁਗਤਾਨ ਦੀ ਪ੍ਰਕਿਰਿਆ ਨਹੀਂ ਕਰਦੇ...",
            summary: "ਸਾਰ",
            quickPay: "ਤੁਰੰਤ ਤਨਖਾਹ",
            gst: "GST",
            mobileNumber: "ਮੋਬਾਇਲ ਨੰਬਰ",
            useAnotherMobile: "ਇਕ ਹੋਰ ਮੋਬਾਈਲ ਨੰਬਰ ਦੀ ਵਰਤੋਂ ਕਰੋ",
            enterOtp: "OTP ਦਰਜ ਕਰੋ",
            resendOtp: "OTP ਨੂੰ ਦੁਬਾਰਾ ਭੇਜੋ",
            availableBalance: "ਉਪਲੱਬਧ ਬਕਾਇਆ",
            refreshBalance: "ਬੈਲੇਂਸ ਚੈੱਕ ਕਰੋ",
            addMoney: "ਪੈਸਾ ਸ਼ਾਮਲ ਕਰੋ",
            insufficientFund: "ਲੋੜੀਂਦੇ ਫੰਡ!",
            rechargeWallet: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਬਟੂਏ ਨੂੰ ਰੀਚਾਰਜ ਕਰੋ ...",
            useAnotherMobileAlt: "ਹੋਰ ਮੋਬਾਈਲ ਨੰਬਰ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਲੌਗਇਨ ਕਰੋ",
            loggedIn: "ਤੁਸੀਂ",
            loggedInAlt: "ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਲੌਗ ਇਨ ਕੀਤਾ ਹੈ",
            payUsingUpi: "UPI ID ਦਾ ਉਪਯੋਗ ਕਰਕੇ ਭੁਗਤਾਨ ਕਰੋ",
            payUsingQr: "QR ਕੋਡ ਦੀ ਵਰਤੋਂ ਕਰੋ"
        },
        urdu: {
            upiQrText: "(براہ کرم کوئی بھی UPI ایپ استعمال کرکے UPI QR اسکین کریں)",
            saveWlText: "آئندہ ادائیگیوں کے لئے اس پرس کو محفوظ کریں",
            saveNbText: "مستقبل میں ادائیگیوں کے لئے اس بینک کو بچائیں",
            expiry: "ختم ہوجانا",
            orderId: "آرڈر کی شناخت",
            amount: "رقم",
            convenienceFee: "سہولت فیس",
            amountPayable: "ادائیگی",
            savedCards: "محفوظ کارڈ",
            savedVpa: "وی پی اے محفوظ کیا",
            savedBanks: "محفوظ کردہ بینکوں",
            savedWallet: "بٹوے محفوظ",
            card: "کارڈس",
            creditCard: "کریڈٹ کارڈ",
            debitCard: "ڈیبٹ کارڈ",
            international: "بین اقوامی",
            upi: "یو پی آئی",
            upiQr: "اسکین اور ادا کریں",
            netBanking: "نیٹ بینکنگ",
            wallet: "وولیٹ",
            paytm: "پی ٹی ایم",
            cashondelivery: "ادائیگی وصولی کے وقت",
            payathotel: "ہوٹل میں ادائیگی کریں",
            payondelivery: "ترسیل پر ادائیگی",
            emi: "ای ایم آئی",
            cardNumber: "کارڈ نمبر",
            checkStartNo: "غلط کارڈ نمبر",
            validCardCheck: "غلط کارڈ نمبر",
            emptyCardNumber: "برائے کرم کارڈ نمبر درج کریں",
            notSupportedCard: "کارڈ کی سہولت نہیں ہے",
            validExpDate: "غلط تاریخ",
            emptyExpiry: "برائے کرم میعاد ختم بھریں",
            cvvTitle: "CVV کیا ہے؟",
            cvvText: "CVV نمبر آپ کے کارڈ کے پچھلے حصے میں آخری تین نمبر ہے",
            btnOk: "ٹھیک ہے",
            cvvValidate: "غلط CVV",
            emptyCvv: "برائے کرم CVV درج کریں",
            nameOnCard: "کارڈ پہ درنام",
            nameError: "برائے کرم نام درج کریں",
            invalidError: "غلط نام",
            saveCardCheckboxText: "آئندہ ادائیگیوں کے لئے اس کارڈ کو محفوظ کریں",
            otherBank: "دوسرے بینک",
            errorBankList: "برائے کرم بینک منتخب کریں",
            vpaAddress: "ورچوئل ادائیگی کا پتہ",
            invalidVpa: "غلط VPA",
            enterVpa: "برائے کرم VPA درج کریں",
            vpaPara: "یو پی آئی آئی ادائیگی کا انوکھا پتہ ہے جو ادائیگی کرنے کیلئے کسی شخص کے بینک اکاؤنٹ سے منسلک ہوتا ہے۔",
            vpaName: "نام",
            invalidVpaName: "غلط نام",
            enterVpaName: "برائے کرم نام درج کریں",
            saveVpaText: " آئندہ ادائیگیوں کے لئے اس VPA کو محفوظ کریں",
            poweredBy: "از: وی بلیٹن:",
            errorWalletList: "برائے کرم وولیٹ کی کوئی بھی قسم منتخب کریں",
            errorCOD: "برائے کرم کیش آن ڈلیوری منتخب کریں",
            emiValue: "ای ایم آئی ویلیو",
            emiInterestText: "سور",
            chargedByBank: "(بینک کے ذریعہ وصول کردہ)",
            totalEmiText: "ماہ کے لئے",
            emiMonthsText: "کل ای ایم آئی",
            cancel: "منسوخ کریں",
            payBtnText: "ادا کریں",
            selectBank: "بینک منتخب کریں",
            selectDebitCredit: "ڈیبٹ / کریڈٹ منتخب کریں",
            emiBankErrorBefore: "کارڈ نمبر درج کریں ",
            emiBankErrorAfter: " برائے کرم",
            emiCardErrorBefore: "نمبر درج کریں ",
            emiCardErrorAfter: "برائے کرم ",
            errorCardDomestic: "برائے کرم ڈومیسٹک کارڈ نمبر درج کریں",
            emiFor: "ماہ کے لئے",
            emiMonths: "،",
            timeExpireTextBefore: "مے ختم ہوگی",
            timeExpireTextAfter: "اس صفحے کی میعاد",
            retryHeading: "ادائیگی ناکام؟ ابھی دوبارہ کوشش کریں",
            retryBtn: "دوبارہ کوشش کریں",
            returnMerchant: "مرچنٹ پر واپس جائیں",
            upiApprovalText: "برائے کرم اپنے UPI ایپ میں ادائیگی منظور کریں",
            upiStopRefresh: "اس صفحے کو رفریش نہ کریں اور نہ ہی بیک بٹن دبائیں",
            seeDetails: "تفصیلات دیکھیں",
            hideDetails: "تفصیلات چھپائیں",
            defaultLoaderText: "براہ کرم انتظار کریں جب تک ہم آپ کی ادائیگی پر کارروائی نہیں کرتے ہیں",
            summary: "خلاصہ",
            quickPay: "فوری تنخواہ",
            gst: "GST",
            mobileNumber: "موبائل نمبر",
            useAnotherMobile: "دوسرا موبائل نمبر استعمال کریں",
            enterOtp: "OTP درج کریں",
            resendOtp: "کو دوبارہ بھیجیں OTP",
            availableBalance: "دستیاب بیلنس",
            refreshBalance: "بیلنس چیک کریں",
            addMoney: "پیسے شامل کریں",
            insufficientFund: "ناکافی فنڈز!",
            rechargeWallet: "براہ کرم اپنا پرس ریچارج کریں ...",
            useAnotherMobileAlt: "دوسرا موبائل نمبر استعمال کرکے لاگ ان کریں",
            loggedIn: "استعمال کرکے لاگ ان ہوئے ہیں",
            loggedInAlt: "یں",
            payUsingUpi: "UPI ID استعمال کرتے ہوئے ادا کریں",
            payUsingQr: "ادائیگی کیو آر کوڈ استعمال کریں"
        },
        tamil: {
            upiQrText: "(எந்த UPI பயன்பாட்டையும் பயன்படுத்தி UPI QR ஐ ஸ்கேன் செய்யுங்கள்)",
            saveWlText: "எதிர்கால கொடுப்பனவுகளுக்கு இந்த பணப்பையை சேமிக்கவும்",
            saveNbText: "எதிர்கால கொடுப்பனவுகளுக்கு இந்த வங்கியைச் சேமிக்கவும்",
            expiry: "காலாவதியாகும்",
            orderId: "ஆர்டர் ஐடி",
            amount: "தொகை",
            convenienceFee: "வசதியான கட்டணம்",
            amountPayable: "செலுத்த வேண்டிய தொகை",
            savedCards: "சேமித்த அட்டைகள்",
            savedVpa: "சேமித்த வி.பி.ஏ.",
            savedBanks: "சேமித்த வங்கிகள்",
            savedWallet: "சேமித்த பணப்பைகள்",
            card: "அட்டைகள்",
            creditCard: "கடன் அட்டை",
            debitCard: "பற்று அட்டை",
            international: "சர்வதேச",
            upi: "யுபிஐ",
            upiQr: "ஸ்கேன் & கட்டணம்",
            netBanking: "நிகர வங்கி",
            wallet: "வாலட்",
            paytm: "Paytm",
            cashondelivery: "கொடுத்ததும் ரொக்கம்",
            payathotel: "ஹோட்டலில் பணம் செலுத்துங்கள்",
            payondelivery: "விநியோகத்தில் செலுத்தவும்",
            emi: "ஏ.ம்.இ",
            cardNumber: "அட்டை எண்",
            checkStartNo: "தவறான அட்டை எண்",
            validCardCheck: "தவறான அட்டை எண்",
            emptyCardNumber: "அட்டை எண்ணை உள்ளிடவும்",
            notSupportedCard: "அட்டை ஆதரிக்கப்படவில்லை",
            validExpDate: "தவறான தேதி",
            emptyExpiry: "காலாவதி உள்ளிடவும்",
            cvvTitle: "சி.வி.வி என்றால் என்ன?",
            cvvText: "உங்கள் அட்டையின் பின்புறத்தில் உள்ள கடைசி மூன்று இலக்கங்கள் சி.வி.வி எண்",
            btnOk: "சரி",
            cvvValidate: "தவறான சி.வி.வி.",
            emptyCvv: "சி.வி.வி ஐ உள்ளிடவும்",
            nameOnCard: "அட்டையிலுள்ள பெயர்",
            nameError: "பெயரை உள்ளிடவும்",
            invalidError: "தவறான பெயர்",
            saveCardCheckboxText: "இந்த அட்டையைச் சேமிக்கவும் எதிர்கால கொடுப்பனவுகளுக்கு",
            otherBank: "பிற வங்கி",
            errorBankList: "வங்கியைத் தேர்ந்தெடுக்கவும்",
            vpaAddress: "மெய்நிகர் கட்டண முகவரி",
            invalidVpa: "தவறான VPA",
            enterVpa: "VPA ஐ உள்ளிடவும்",
            vpaPara: "யுபிஐ ஐடி என்பது ஒரு தனித்துவமான கட்டண முகவரி, இது பணம் செலுத்துவதற்கு ஒரு நபரின் வங்கி கணக்கில் இணைக்கப்பட்டுள்ளது.",
            vpaName: "பெயர்",
            invalidVpaName: "தவறான பெயர்",
            enterVpaName: "பெயரை உள்ளிடவும்",
            saveVpaText: "இந்த VPA ஐ சேமிக்கவும் எதிர்கால கொடுப்பனவுகளுக்கு",
            poweredBy: "இயக்கப்படுகிறது:",
            errorWalletList: "எந்த பணப்பை வகையையும் தேர்வு செய்யவும்",
            errorCOD: "COD ஐத் தேர்ந்தெடுக்கவும்",
            emiValue: "எமி மதிப்பு",
            emiInterestText: "ஆர்வம்",
            chargedByBank: "(வங்கியால் வசூலிக்கப்படுகிறது)",
            totalEmiText: "",
            emiMonthsText: "மாதங்களுக்கு மொத்த ஈ.எம்.ஐ.",
            cancel: "ரத்துசெய்",
            payBtnText: "செலுத்துங்கள்",
            selectBank: "வங்கியைத் தேர்ந்தெடுக்கவும்",
            selectDebitCredit: "பற்று/கடன் தேர்ந்தெடுக்கவும்",
            emiBankErrorBefore: "",
            emiBankErrorAfter: " அட்டை எண்ணை உள்ளிடவும்",
            emiCardErrorBefore: "",
            emiCardErrorAfter: " எண்ணை உள்ளிடவும்",
            errorCardDomestic: "உள்நாட்டு அட்டை எண்ணை உள்ளிடவும்",
            emiFor: ",",
            emiMonths: "மாதங்களுக்கு",
            timeExpireTextBefore: "இந்த பக்கம்",
            timeExpireTextAfter: "இல் காலாவதி இருக்கும்",
            retryHeading: "கட்டணம் தோல்வியடைந்ததா? மீண்டும் முயற்சிக்கவும்",
            retryBtn: "மீண்டும் முயற்சிக்கவும்",
            returnMerchant: "வணிகருக்குத் திரும்பு",
            upiApprovalText: "உங்கள் UPI பயன்பாட்டில் கட்டணம் செலுத்துவதை அங்கீகரிக்கவும்",
            upiStopRefresh: "இந்தப் பக்கத்தைப் புதுப்பிக்க வேண்டாம் அல்லது பின் பொத்தானை அழுத்தவும்",
            seeDetails: "விவரங்களைக் காண்க",
            hideDetails: "விவரங்களை மறை",
            defaultLoaderText: "உங்கள் கட்டணத்தை நாங்கள் செயலாக்கும்போது காத்திருக்கவும்...",
            summary: "சுருக்கம்",
            quickPay: "விரைவான ஊதியம்",
            gst: "GST",
            mobileNumber: "கைபேசி எண்",
            useAnotherMobile: "மற்றொரு மொபைல் எண்ணைப் பயன்படுத்தவும்",
            enterOtp: "OTP ஐ உள்ளிடவும்",
            resendOtp: "OTP ஐ மீண்டும் அனுப்பு",
            availableBalance: "கிடைக்கும் இருப்பு",
            refreshBalance: "இருப்பு சரிபார்க்கவும்",
            addMoney: "பணம் சேர்க்கவும்",
            insufficientFund: "போதிய நிதி இல்லை!",
            rechargeWallet: "உங்கள் பணப்பையை ரீசார்ஜ் செய்யுங்கள் ...",
            useAnotherMobileAlt: "மற்றொரு மொபைல் எண்ணைப் பயன்படுத்தி உள்நுழைக",
            loggedIn: "நீங்கள்",
            loggedInAlt: "ஐப் பயன்படுத்தி உள்நுழைந்துள்ளீர்கள்",
            payUsingUpi: "UPI ஐடியைப் பயன்படுத்தவும்",
            payUsingQr: "QR குறியீட்டைப் பயன்படுத்தவும்"
        },
        telugu: {
            upiQrText: "(ఏదైనా యుపిఐ యాప్ ఉపయోగించి యుపిఐ క్యూఆర్ స్కాన్ చేయండి)",
            saveWlText: "భవిష్యత్ చెల్లింపుల కోసం ఈ వాలెట్‌ను సేవ్ చేయండి",
            saveNbText: "భవిష్యత్ చెల్లింపుల కోసం ఈ బ్యాంకును సేవ్ చేయండి",
            expiry: "గడువు",
            orderId: "ఆర్డర్ గుర్తింపు సంఖ్యా",
            amount: "మొత్తం",
            convenienceFee: "సౌకర్య రుసుము",
            amountPayable: "చెల్లించవలసిన మొత్తం",
            savedCards: "కార్డులు సేవ్ చేయబడ్డాయి",
            savedVpa: "VPA సేవ్ చేయబడింది",
            savedBanks: "సేవ్ చేసిన బ్యాంకులు",
            savedWallet: "వాలెట్లను సేవ్ చేసింది",
            card: "కార్డులు",
            creditCard: "క్రెడిట్ కార్డ్",
            debitCard: "డెబిట్ కార్డ్",
            international: "అంతర్జాతీయ",
            upi: "యూ.ప్.ఐ",
            upiQr: "స్కాన్ & పే",
            netBanking: "నెట్ బ్యాంకింగ్",
            wallet: "వాలెట్",
            paytm: "Paytm",
            cashondelivery: "నగదు ఆన్ డెలివరీ",
            payathotel: "హోటల్‌లో చెల్లించండి",
            payondelivery: "డెలివరీపై చెల్లించండి",
            emi: "ఏ.ఎం.ఐ",
            cardNumber: "కార్డు సంఖ్య",
            checkStartNo: "చెల్లని కార్డ్ సంఖ్య",
            validCardCheck: "చెల్లని కార్డ్ సంఖ్య",
            emptyCardNumber: "దయచేసి కార్డ్ నంబర్‌ను నమోదు చేయండి",
            notSupportedCard: "కార్డు మద్దతు లేదు",
            validExpDate: "చెల్లని తేదీ",
            emptyExpiry: "గడువు నమోదు చేయండి",
            cvvTitle: "సివివి అంటే ఏమిటి?",
            cvvText: "CVV సంఖ్య మీ కార్డు వెనుక చివరి మూడు అంకెలు",
            btnOk: "సరే",
            cvvValidate: "చెల్లని CVV",
            emptyCvv: "CVV నమోదు చేయండి",
            nameOnCard: "కర్డుపై పేరు",
            nameError: "దయచేసి పేరు నమోదు చేయండి",
            invalidError: "చెల్లని పేరు",
            saveCardCheckboxText: "భవిష్యత్ చెల్లింపుల కోసం ఈ కార్డును సేవ్ చేయండి",
            otherBank: "ఇతర బ్యాంకు",
            errorBankList: "దయచేసి బ్యాంకును ఎంచుకోండి",
            vpaAddress: "వర్చువల్ చెల్లింపు చిరునామా",
            invalidVpa: "చెల్లని VPA",
            enterVpa: "దయచేసి VPA ని నమోదు చేయండి",
            vpaPara: "యుపిఐ ఐడి అనేది ఒక ప్రత్యేకమైన చెల్లింపు చిరునామా, ఇది చెల్లింపులు చేయడానికి ఒక వ్యక్తి యొక్క బ్యాంక్ ఖాతాతో అనుసంధానించబడుతుంది.",
            vpaName: "పేరు",
            invalidVpaName: "చెల్లని పేరు",
            enterVpaName: "దయచేసి పేరు నమోదు చేయండి",
            saveVpaText: "భవిష్యత్ చెల్లింపుల కోసం ఈ VPA ని సేవ్ చేయండి",
            poweredBy: "ఆధారితం:",
            errorWalletList: "దయచేసి ఏదైనా వాలెట్ రకాన్ని ఎంచుకోండి",
            errorCOD: "దయచేసి COD ని ఎంచుకోండి",
            emiValue: "EMI విలువ",
            emiInterestText: "వడ్డీ",
            chargedByBank: "(బ్యాంక్ వసూలు చేస్తుంది)",
            totalEmiText: "",
            emiMonthsText: "నెలల మొత్తం EMI",
            cancel: "రద్దు",
            payBtnText: "చెల్లించటానికి",
            selectBank: "బ్యాంకును ఎంచుకోండి",
            selectDebitCredit: "డెబిట్ / క్రెడిట్ ఎంచుకోండి",
            emiBankErrorBefore: "దయచేసి ",
            emiBankErrorAfter: "కార్డ్ నంబర్‌ను నమోదు చేయండి",
            emiCardErrorBefore: "దయచేసి ",
            emiCardErrorAfter: " సంఖ్యను నమోదు చేయండి",
            errorCardDomestic: "డొమెస్టిక్ కార్డు సంఖ్యను నమోదు చేయండి",
            emiFor: ",",
            emiMonths: "నెలలు",
            timeExpireTextBefore: "ఈ పేజీ",
            timeExpireTextAfter: "లో ముగుస్తుంది",
            retryHeading: "చెల్లింపు విఫలమైంది? ఇప్పుడు మళ్లీ ప్రయత్నించండి",
            retryBtn: "మళ్ళీ ప్రయత్నించు",
            returnMerchant: "వ్యాపారికి తిరిగి వెళ్ళు",
            upiApprovalText: "దయచేసి మీ యుపిఐ యాప్‌లో చెల్లింపును ఆమోదించండి",
            upiStopRefresh: "ఈ పేజీని రిఫ్రెష్ చేయవద్దు లేదా వెనుక బటన్ నొక్కండి",
            seeDetails: "వివరములు చూడు",
            hideDetails: "వివరాలను దాచండి",
            defaultLoaderText: "మేము మీ చెల్లింపును ప్రాసెస్ చేసేటప్పుడు వేచి ఉండండి...",
            summary: "సారాంశం",
            quickPay: "శీఘ్ర చెల్లింపు",
            gst: "GST",
            mobileNumber: "మొబైల్ సంఖ్య",
            useAnotherMobile: "మరొక మొబైల్ నంబర్‌ను ఉపయోగించండి",
            enterOtp: "OTP ని నమోదు చేయండి",
            resendOtp: "OTP ను మళ్ళీ పంపు",
            availableBalance: "అందుబాటులో ఉన్న బ్యాలెన్స్",
            refreshBalance: "బ్యాలెన్స్ తనిఖీ చేయండి",
            addMoney: "డబ్బు జోడించండి",
            insufficientFund: "తగినంత నిధులు లేవు!",
            rechargeWallet: "దయచేసి మీ వాలెట్‌ను రీఛార్జ్ చేయండి ...",
            useAnotherMobileAlt: "మరొక మొబైల్ నంబర్ ఉపయోగించి లాగిన్ అవ్వండి",
            loggedIn: "మీరు",
            loggedInAlt: "ఉపయోగించి లాగిన్ అయ్యారు",
            payUsingUpi: "UPI ID ని ఉపయోగించడం చెల్లించండి",
            payUsingQr: "QR కోడ్‌ను ఉపయోగించడం చెల్లించండి"
        },
        french: {
            upiQrText: "(Veuillez scanner UPI QR en utilisant n'importe quelle application UPI)",
            saveWlText: "Conservez ce portefeuille pour vos futurs paiements",
            saveNbText: "Enregistrez cette banque pour vos futurs paiements",
            expiry: "Expiration",
            orderId: "Numéro de commande",
            amount: "Montant",
            convenienceFee: "Frais de commodité",
            amountPayable: "Montant dû",
            savedCards: "Cartes enregistrées",
            savedVpa: "VPA enregistré",
            savedBanks: "Banques enregistrées",
            savedWallet: "Portefeuilles enregistrés",
            card: "Les cartes",
            creditCard: "Carte de crédit",
            debitCard: "Carte de débit",
            international: "Internationale",
            upi: "UPI",
            upiQr: "Scanner et payer",
            netBanking: "Banque nette",
            wallet: "Portefeuille",
            paytm: "Paytm",
            cashondelivery: "Paiement à la livraison",
            payathotel: "Payez à l'hôtel",
            payondelivery: "payer à la livraison",
            emi: "EMI",
            cardNumber: "Numéro de carte",
            checkStartNo: "Numéro de carte invalide",
            validCardCheck: "Numéro de carte invalide",
            emptyCardNumber: "Veuillez saisir le numéro de carte",
            notSupportedCard: "Carte non prise en charge",
            validExpDate: "Date invalide",
            emptyExpiry: "Veuillez saisir l'expiration",
            cvvTitle: "Qu'est-ce que le CVV?",
            cvvText: "Le numéro CVV est composé de trois chiffres au dos de votre carte",
            btnOk: "D'accord",
            cvvValidate: "CVV invalide",
            emptyCvv: "Veuillez entrer CVV",
            nameOnCard: "Nom sur la carte",
            nameError: "Veuillez saisir un nom",
            invalidError: "Nom invalide",
            saveCardCheckboxText: "Enregistrez cette carte pour les paiements futurs",
            otherBank: "Autre banque",
            errorBankList: "Veuillez sélectionner une banque",
            vpaAddress: "Adresse de paiement virtuelle",
            invalidVpa: "VPA invalide",
            enterVpa: "Veuillez saisir VPA",
            vpaPara: "L'ID UPI est une adresse de paiement unique qui est liée au compte bancaire d'une personne pour effectuer des paiements.",
            vpaName: "Nom",
            invalidVpaName: "Nom invalide",
            enterVpaName: "Veuillez saisir un nom",
            saveVpaText: "Enregistrer cet VPA pour les paiements futurs",
            poweredBy: "Alimenté par:",
            errorWalletList: "Veuillez choisir n'importe quel type de portefeuille",
            errorCOD: "Veuillez choisir COD",
            emiValue: "Valeur EMI",
            emiInterestText: "Intérêt",
            chargedByBank: "(facturé par la Banque)",
            totalEmiText: "EMI total pendant",
            emiMonthsText: "mois",
            cancel: "Annuler",
            payBtnText: "Payer",
            selectBank: "sélectionner la banque",
            selectDebitCredit: "Sélectionnez Débit / Crédit",
            emiBankErrorBefore: "Veuillez saisir numéro carte ",
            emiBankErrorAfter: "",
            emiCardErrorBefore: "Veuillez saisir numéro ",
            emiCardErrorAfter: "",
            errorCardDomestic: "Veuillez saisir numéro carte domestic",
            emiFor: "pour",
            emiMonths: "mois",
            timeExpireTextBefore: "Cette page expirera dans",
            timeExpireTextAfter: "",
            retryHeading: "Paiement échoué? Réessayer maintenant",
            retryBtn: "Réessayez",
            returnMerchant: "Retourner au marchand",
            upiApprovalText: "Veuillez approuver le paiement dans votre application UPI",
            upiStopRefresh: "Ne rafraîchissez pas cette page et n'appuyez pas sur le bouton de retour",
            seeDetails: "Voir les détails",
            hideDetails: "Cacher les détails",
            defaultLoaderText: "Veuillez patienter pendant que nous traitons votre paiement...",
            summary: "sommaire",
            quickPay: "Paiement rapide",
            gst: "GST",
            mobileNumber: "Numéro de portable",
            useAnotherMobile: "Utiliser un autre numéro de mobile",
            enterOtp: "Entrez OTP",
            resendOtp: "Renvoyer OTP",
            availableBalance: "Solde disponible",
            refreshBalance: "Vérifier le solde",
            addMoney: "Ajouter de l'argent",
            insufficientFund: "Insufficient funds!",
            rechargeWallet: "Veuillez recharger votre portefeuille ...",
            useAnotherMobileAlt: "Connectez-vous en utilisant un autre numéro de mobile",
            loggedIn: "Vous êtes connecté en utilisant",
            loggedInAlt: "",
            payUsingUpi: "PAYER EN UTILISANT L'ID UPI",
            payUsingQr: "PAYER PAR QR CODE"
        },
        spanish: {
            upiQrText: "(Escanee UPI QR usando cualquier aplicación UPI)",
            saveWlText: "Guarde esta billetera para pagos futuros",
            saveNbText: "Guarde este banco para pagos futuros",
            expiry: "Expiración",
            orderId: "ID de pedido",
            amount: "Cantidad",
            convenienceFee: "Costes de Gestión",
            amountPayable: "Cantidad pagable",
            savedCards: "Tarjetas guardadas",
            savedVpa: "VPA guardada",
            savedBanks: "Bancos guardados",
            savedWallet: "Billeteras guardadas",
            card: "Las cartas",
            creditCard: "Tarjeta de crédito",
            debitCard: "Tarjeta de débito",
            international: "Internacional",
            upi: "UPI",
            upiQr: "Escanear y pagar",
            netBanking: "Banca Neta",
            wallet: "Billetera",
            paytm: "Paytm",
            cashondelivery: "Contra reembolso",
            payathotel: "Pagar en el hotel",
            payondelivery: "pagar cuando reciba",
            emi: "EMI",
            cardNumber: "Número de tarjeta",
            checkStartNo: "Numero de tarjeta invalido",
            validCardCheck: "Numero de tarjeta invalido",
            emptyCardNumber: "Por favor, introduzca el número de tarjeta",
            notSupportedCard: "Tarjeta no admitida",
            validExpDate: "Fecha invalida",
            emptyExpiry: "Por favor, introduzca la caducidad",
            cvvTitle: "¿Qué es el CVV?",
            cvvText: "El número CVV son los últimos tres dígitos en el reverso de su tarjeta.",
            btnOk: "Ok",
            cvvValidate: "CVV inválido",
            emptyCvv: "Por favor, introduzca CVV",
            nameOnCard: "Nombre en la tarjeta",
            nameError: "Por favor, introduzca el nombre",
            invalidError: "Nombre inválido",
            saveCardCheckboxText: "Guarde esta tarjeta para pagos futuros",
            otherBank: "Otro banco",
            errorBankList: "Por favor seleccione banco",
            vpaAddress: "Dirección de pago virtual",
            invalidVpa: "VPA inválido",
            enterVpa: "Por favor, introduzca VPA",
            vpaPara: "UPI ID es una dirección de pago única que está vinculada a la cuenta bancaria de una persona para realizar pagos.",
            vpaName: "Nombre",
            invalidVpaName: "Nombre inválido",
            enterVpaName: "Por favor, introduzca el nombre",
            saveVpaText: "Guarde este VPA para pagos futuros",
            poweredBy: "Energizado por:",
            errorWalletList: "Por favor, elija cualquier tipo de billetera",
            errorCOD: "Por favor elija COD",
            emiValue: "Valor EMI",
            emiInterestText: "Interesar",
            chargedByBank: "(cobrado por el banco)",
            totalEmiText: "EMI total por",
            emiMonthsText: "meses",
            cancel: "Cancelar",
            payBtnText: "Hacer el pago",
            selectBank: "seleccione banco",
            selectDebitCredit: "Seleccione débito / crédito",
            emiBankErrorBefore: "Ingrese el número de tarjeta ",
            emiBankErrorAfter: "",
            emiCardErrorBefore: "Por favor ingrese número ",
            emiCardErrorAfter: "",
            errorCardDomestic: "Por favor, introduzca número tarjeta domestic",
            emiFor: "durante",
            emiMonths: "meses",
            timeExpireTextBefore: "Esta página expirará en",
            timeExpireTextAfter: "",
            retryHeading: "¿Pago fallido? Reintentar ahora",
            retryBtn: "Procesar de nuevo",
            returnMerchant: "Volver al comerciante",
            upiApprovalText: "Apruebe el pago en su aplicación UPI",
            upiStopRefresh: "No actualice esta página ni presione el botón Atrás",
            seeDetails: "Ver detalles",
            hideDetails: "Ocultar detalles",
            defaultLoaderText: "Espere mientras procesamos su pago...",
            summary: "resumen",
            quickPay: "Pago rapido",
            gst: "GST",
            mobileNumber: "número de teléfono móvil",
            useAnotherMobile: "Utilice otro número de móvil",
            enterOtp: "Ingrese OTP",
            resendOtp: "Reenviar OTP",
            availableBalance: "Saldo disponible",
            refreshBalance: "Consultar saldo",
            addMoney: "Agregar dinero",
            insufficientFund: "Fonds insuffisants!",
            rechargeWallet: "Recargue su billetera ...",
            useAnotherMobileAlt: "Iniciar sesión con otro número de móvil",
            loggedIn: "Ha iniciado sesión con",
            loggedInAlt: "",
            payUsingUpi: "PAGAR CON UPI ID",
            payUsingQr: "PAGAR CON CÓDIGO QR"
        },
        marathi: {
            upiQrText: "(कृपया कोणतेही यूपीआय अ‍ॅप वापरुन यूपीआय क्यूआर स्कॅन करा)",
            saveWlText: "हे पाकीट भविष्यातील देयकासाठी जतन करा",
            saveNbText: "भविष्यातील पेमेंटसाठी ही बँक जतन करा",
            expiry: "कालबाह्यता",
            orderId: "ऑर्डर आयडी",
            amount: "रक्कम",
            convenienceFee: "सुविधा शुल्क",
            amountPayable: "देय रक्कम",
            savedCards: "जतन केलेली कार्डे",
            savedVpa: "व्हीपीए जतन केले",
            savedBanks: "जतन बँका",
            savedWallet: "जतन केलेले पाकिटे",
            card: "कार्डे",
            creditCard: "क्रेडीट कार्ड",
            debitCard: "डेबिट कार्ड",
            international: "आंतरराष्ट्रीय",
            upi: "यू.पी.आय",
            upiQr: "स्कॅन आणि पे",
            netBanking: "नेट बँकिंग",
            wallet: "पाकीट",
            paytm: "पेटीएम",
            cashondelivery: "घरपोच दिल्यावर रोख रक्कम",
            payathotel: "हॉटेलमध्ये पैसे द्या",
            payondelivery: "वितरणावर पैसे द्या",
            emi: "ई.एम.आय",
            cardNumber: "कार्ड क्रमांक",
            checkStartNo: "अवैध्य पत्रक क्रमांक",
            validCardCheck: "अवैध्य पत्रक क्रमांक",
            emptyCardNumber: "कृपया कार्ड क्रमांक प्रविष्ट करा",
            notSupportedCard: "कार्ड समर्थित नाही",
            validExpDate: "अवैध तारीख",
            emptyExpiry: "कृपया समाप्ती प्रविष्ट करा",
            cvvTitle: "सीव्हीव्ही म्हणजे काय?",
            cvvText: "आपल्या कार्डाच्या मागील बाजूस सीव्हीव्ही क्रमांक शेवटचा तीन अंक आहे",
            btnOk: "ठीक आहे",
            cvvValidate: "अवैध सीव्हीव्ही",
            emptyCvv: "कृपया सीव्हीव्ही प्रविष्ट करा",
            nameOnCard: "कार्डवर नाव",
            nameError: "कृपया नाव प्रविष्ट करा",
            invalidError: "अवैध नाव",
            saveCardCheckboxText: "हे कार्ड भविष्यातील देयकासाठी जतन करा",
            otherBank: "इतर बँक",
            errorBankList: "कृपया बँक निवडा",
            vpaAddress: "व्हर्च्युअल पेमेंट पत्ता",
            invalidVpa: "अवैध व्हीपीए",
            enterVpa: "कृपया व्हीपीए प्रविष्ट करा",
            vpaPara: "यूपीआय आयडी हा एक अनोखा पेमेंट पत्ता आहे जो एखाद्या व्यक्तीच्या बँक खात्यात पैसे भरण्यासाठी जोडलेला असतो.",
            vpaName: "नाव",
            invalidVpaName: "अवैध नाव",
            enterVpaName: "कृपया नाव प्रविष्ट करा",
            saveVpaText: "भविष्यातील देयकासाठी हा व्हीपीए जतन करा",
            poweredBy: "द्वारा समर्थित:",
            errorWalletList: "कृपया कोणताही वॉलेट प्रकार निवडा",
            errorCOD: "कृपया COD निवडा",
            emiValue: "ईएमआय मूल्य",
            emiInterestText: "व्याज",
            chargedByBank: "(बँकेने आकारलेले)",
            totalEmiText: "",
            emiMonthsText: "महिन्यांसाठी एकूण ईएमआय",
            cancel: "रद्द करा",
            payBtnText: "देय द्या",
            selectBank: "बँक निवडा",
            selectDebitCredit: "डेबिट / क्रेडिट निवडा",
            emiBankErrorBefore: "कृपया ",
            emiBankErrorAfter: " कार्ड क्रमांक प्रविष्ट करा",
            emiCardErrorBefore: "कृपया ",
            emiCardErrorAfter: " नंबर प्रविष्ट करा",
            errorCardDomestic: "कृपया डोमेस्टिक कार्ड क्रमांक प्रविष्ट करा",
            emiFor: ",",
            emiMonths: "महिने",
            timeExpireTextBefore: "हे पृष्ठ",
            timeExpireTextAfter: "वाजता कालबाह्य होईल",
            retryHeading: "देयक अयशस्वी झाले? आता पुन्हा प्रयत्न करा",
            retryBtn: "पुन्हा प्रयत्न करा",
            returnMerchant: "मर्चंटकडे परत या",
            upiApprovalText: "कृपया आपल्या यूपीआय अॅपमधील देय मंजूर करा",
            upiStopRefresh: "हे पृष्ठ रीफ्रेश करू नका किंवा परत बटण दाबा",
            seeDetails: "तपशील बघा",
            hideDetails: "माहिती लपवा",
            defaultLoaderText: "आम्ही आपल्या देयकावर प्रक्रिया करेपर्यंत प्रतीक्षा करा...",
            summary: "सारांश",
            quickPay: "द्रुत वेतन",
            gst: "GST",
            mobileNumber: "मोबाइल नंबर",
            useAnotherMobile: "दुसरा मोबाइल नंबर वापरा",
            enterOtp: "OTP प्रविष्ट करा",
            resendOtp: "OTP पुन्हा पाठवा",
            availableBalance: "उपलब्ध शिल्लक",
            refreshBalance: "शिल्लक तपासा",
            addMoney: "पैसे जोडा",
            insufficientFund: "अपुरा निधी!",
            rechargeWallet: "कृपया आपले पाकीट रिचार्ज करा ...",
            useAnotherMobileAlt: "दुसरा मोबाइल नंबर वापरुन लॉगिन करा",
            loggedIn: "आपण",
            loggedInAlt: "वापरुन लॉग इन केले आहे",
            payUsingUpi: "यूपीआय आयडी वापरुन द्या",
            payUsingQr: "क्यूआर कोड वापरुन द्या"
        },
        malayalam: {
            upiQrText: "(ഏതെങ്കിലും യുപിഐ ആപ്പ് ഉപയോഗിച്ച് യുപിഐ ക്യുആർ സ്കാൻ ചെയ്യുക)",
            saveWlText: "ഭാവി പേയ്‌മെന്റുകൾക്കായി ഈ വാലറ്റ് സംരക്ഷിക്കുക",
            saveNbText: "ഭാവി പേയ്‌മെന്റുകൾക്കായി ഈ ബാങ്ക് സംരക്ഷിക്കുക",
            expiry: "കാലഹരണപ്പെടുന്നു",
            orderId: "ഓർഡർ ഐഡി",
            amount: "തുക",
            convenienceFee: "സൗകര്യ ഫീസ്",
            amountPayable: "നൽകേണ്ട തുക",
            savedCards: "കാർഡുകൾ സംരക്ഷിച്ചു",
            savedVpa: "VPA സംരക്ഷിച്ചു",
            savedBanks: "ബാങ്കുകൾ സംരക്ഷിച്ചു",
            savedWallet: "വാലറ്റുകൾ സംരക്ഷിച്ചു",
            card: "കാർഡുകൾ",
            creditCard: "ക്രെഡിറ്റ് കാർഡ്",
            debitCard: "ഡെബിറ്റ് കാർഡ്",
            international: "അന്താരാഷ്ട്ര",
            upi: "യുപിഐ",
            upiQr: "സ്‌കാൻ ചെയ്‌ത് പണമടയ്‌ക്കുക",
            netBanking: "നെറ്റ് ബാങ്കിംഗ്",
            wallet: "വാലറ്റ്",
            paytm: "പേടിഎം",
            cashondelivery: "ക്യാഷ് ഓൺ ഡെലിവറി",
            payathotel: "ഹോട്ടലിൽ പണമടയ്‌ക്കുക",
            payondelivery: "ഡെലിവറിക്ക് പണം നൽകുക",
            emi: "ഇ.എം.ഐ",
            cardNumber: "കാർഡ് നമ്പർ",
            checkStartNo: "കാർഡ് നമ്പർ അസാധുവാണ്",
            validCardCheck: "കാർഡ് നമ്പർ അസാധുവാണ്",
            emptyCardNumber: "കാർഡ് നമ്പർ നൽകുക",
            notSupportedCard: "കാർഡ് പിന്തുണയ്‌ക്കുന്നില്ല",
            validExpDate: "അസാധുവായ തീയതി",
            emptyExpiry: "കാലഹരണപ്പെടൽ നൽകുക",
            cvvTitle: "എന്താണ് സിവി‌വി?",
            cvvText: "നിങ്ങളുടെ കാർഡിന് പുറകിലുള്ള അവസാന മൂന്ന് അക്കങ്ങളാണ് സിവി‌വി നമ്പർ",
            btnOk: "ശരി",
            cvvValidate: "അസാധുവായ സിവി‌വി",
            emptyCvv: "സിവി‌വി നൽകുക",
            nameOnCard: "കാർഡിലെ പേര്",
            nameError: "ദയവായി പേര് നൽകുക",
            invalidError: "അസാധുവായ പേര്",
            saveCardCheckboxText: "ഭാവിയിലെ പേയ്‌മെന്റുകൾക്കായി ഈ കാർഡ് സംരക്ഷിക്കുക",
            otherBank: "മറ്റ് ബാങ്ക്",
            errorBankList: "ദയവായി ബാങ്ക് തിരഞ്ഞെടുക്കുക",
            vpaAddress: "വെർച്വൽ പേയ്‌മെന്റ് വിലാസം",
            invalidVpa: "അസാധുവായ VPA",
            enterVpa: "ദയവായി VPA നൽകുക",
            vpaPara: "പേയ്‌മെന്റുകൾ നടത്തുന്നതിന് ഒരു വ്യക്തിയുടെ ബാങ്ക് അക്കൗണ്ടുമായി ലിങ്കുചെയ്‌തിരിക്കുന്ന ഒരു അദ്വിതീയ പേയ്‌മെന്റ് വിലാസമാണ് യുപിഐ ഐഡി.",
            vpaName: "പേര്",
            invalidVpaName: "അസാധുവായ പേര്",
            enterVpaName: "ദയവായി പേര് നൽകുക",
            saveVpaText: "ഭാവിയിലെ പേയ്‌മെന്റുകൾക്കായി ഈ VPA സംരക്ഷിക്കുക",
            poweredBy: "പ്രായോജകർ:",
            errorWalletList: "ഏതെങ്കിലും വാലറ്റ് തരം തിരഞ്ഞെടുക്കുക",
            errorCOD: "COD തിരഞ്ഞെടുക്കുക",
            emiValue: "EMI മൂല്യം",
            emiInterestText: "താൽപ്പര്യം",
            chargedByBank: "(ബാങ്ക് ഈടാക്കിയത്)",
            totalEmiText: "",
            emiMonthsText: "മാസത്തേക്ക് ആകെ ഇ.എം.ഐ.",
            cancel: "റദ്ദാക്കുക",
            payBtnText: "പണമടയ്‌ക്കുക",
            selectBank: "ബാങ്ക് തിരഞ്ഞെടുക്കുക",
            selectDebitCredit: "ഡെബിറ്റ് / ക്രെഡിറ്റ് തിരഞ്ഞെടുക്കുക",
            emiBankErrorBefore: "",
            emiBankErrorAfter: " കാർഡ് നമ്പർ നൽകുക",
            emiCardErrorBefore: "",
            emiCardErrorAfter: " നമ്പർ നൽകുക",
            errorCardDomestic: "ഡൊമസ്റ്റിക് കാർഡ് നമ്പർ നൽകുക",
            emiFor: ",",
            emiMonths: "മാസത്തേക്ക്",
            timeExpireTextBefore: "ഈ പേജ്",
            timeExpireTextAfter: "ൽ കാലഹരണപ്പെടും",
            retryHeading: "പേയ്‌മെന്റ് പരാജയപ്പെട്ടോ? ഇപ്പോൾ വീണ്ടും ശ്രമിക്കുക",
            retryBtn: "വീണ്ടും ശ്രമിക്കുക",
            returnMerchant: "വ്യാപാരിയിലേക്ക് മടങ്ങുക",
            upiApprovalText: "നിങ്ങളുടെ യുപിഐ അപ്ലിക്കേഷനിലെ പേയ്‌മെന്റ് അംഗീകരിക്കുക",
            upiStopRefresh: "ഈ പേജ് പുതുക്കരുത് അല്ലെങ്കിൽ ബാക്ക് ബട്ടൺ അമർത്തരുത്",
            seeDetails: "വിശദാംശങ്ങൾ കാണുക",
            hideDetails: "വിശദാംശങ്ങൾ മറയ്‌ക്കുക",
            defaultLoaderText: "ഞങ്ങൾ നിങ്ങളുടെ പേയ്‌മെന്റ് പ്രോസസ്സ് ചെയ്യുമ്പോൾ കാത്തിരിക്കുക...",
            summary: "സംഗ്രഹം",
            quickPay: "ദ്രുത വേതനം",
            gst: "GST",
            mobileNumber: "മൊബൈൽ നമ്പർ",
            useAnotherMobile: "മറ്റൊരു മൊബൈൽ നമ്പർ ഉപയോഗിക്കുക",
            enterOtp: "OTP നൽകുക",
            resendOtp: "OTP വീണ്ടും അയയ്‌ക്കുക",
            availableBalance: "ലഭ്യമായ ബാലൻസ്",
            refreshBalance: "ബാലൻസ് പരിശോധിക്കുക",
            addMoney: "പണം ചേർക്കുക",
            insufficientFund: "മതിയായ ഫണ്ടുകൾ ഇല്ല!",
            rechargeWallet: "നിങ്ങളുടെ വാലറ്റ് റീചാർജ് ചെയ്യുക ...",
            useAnotherMobileAlt: "മറ്റൊരു മൊബൈൽ നമ്പർ ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക",
            loggedIn: "",
            loggedInAlt: "ഉപയോഗിച്ച് നിങ്ങൾ ലോഗിൻ ചെയ്തിട്ടുണ്ട്",
            payUsingUpi: "യുപിഐ ഐഡി ഉപയോഗിക്കുന്നത് അടയ്ക്കുക",
            payUsingQr: "QR കോഡ് ഉപയോഗിച്ച് പണമടയ്‌ക്കുക"
        },
        kannada: {
            upiQrText: "(ಯಾವುದೇ ಯುಪಿಐ ಅಪ್ಲಿಕೇಶನ್ ಬಳಸಿ ದಯವಿಟ್ಟು ಯುಪಿಐ ಕ್ಯೂಆರ್ ಅನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ)",
            saveWlText: "ಭವಿಷ್ಯದ ಪಾವತಿಗಳಿಗಾಗಿ ಈ ವ್ಯಾಲೆಟ್ ಅನ್ನು ಉಳಿಸಿ",
            saveNbText: "ಭವಿಷ್ಯದ ಪಾವತಿಗಳಿಗಾಗಿ ಈ ಬ್ಯಾಂಕ್ ಅನ್ನು ಉಳಿಸಿ",
            expiry: "ಮುಕ್ತಾಯ",
            orderId: "ಆರ್ಡರ್ ಐಡಿ",
            amount: "ಮೊತ್ತ",
            convenienceFee: "ಅನುಕೂಲಕರ ಶುಲ್ಕ",
            amountPayable: "ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ",
            savedCards: "ಉಳಿಸಿದ ಕಾರ್ಡ್‌ಗಳು",
            savedVpa: "ವಿಪಿಎ ಉಳಿಸಲಾಗಿದೆ",
            savedBanks: "ಉಳಿಸಿದ ಬ್ಯಾಂಕುಗಳು",
            savedWallet: "ಉಳಿಸಿದ ತೊಗಲಿನ ಚೀಲಗಳು",
            card: "ಕಾರ್ಡ್‌ಗಳು",
            creditCard: "ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್",
            debitCard: "ಡೆಬಿಟ್ ಕಾರ್ಡ್",
            international: "ಅಂತಾರಾಷ್ಟ್ರೀಯ",
            upi: "ಯುಪಿಐ",
            upiQr: "ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಮತ್ತು ಪಾವತಿಸಿ",
            netBanking: "ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್",
            wallet: "ಕೈಚೀಲ",
            paytm: "Paytm",
            cashondelivery: "ತಲುಪಿದಾಗ ಹಣ ಪಾವತಿ",
            payathotel: "ಹೋಟೆಲ್ನಲ್ಲಿ ಪಾವತಿಸಿ",
            payondelivery: "ವಿತರಣೆಯಲ್ಲಿ ಪಾವತಿಸಿ",
            emi: "ಇ.ಎಂ.ಐ",
            cardNumber: "ಕಾರ್ಡ್ ಸಂಖ್ಯೆ",
            checkStartNo: "ಅಮಾನ್ಯವಾದ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ",
            validCardCheck: "ಅಮಾನ್ಯವಾದ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ",
            emptyCardNumber: "ದಯವಿಟ್ಟು ಕಾರ್ಡ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
            notSupportedCard: "ಕಾರ್ಡ್ ಬೆಂಬಲಿಸುವುದಿಲ್ಲ",
            validExpDate: "ಅಮಾನ್ಯ ದಿನಾಂಕ",
            emptyExpiry: "ದಯವಿಟ್ಟು ಅವಧಿ ನಮೂದಿಸಿ",
            cvvTitle: "ಸಿವಿವಿ ಎಂದರೇನು?",
            cvvText: "ಸಿವಿವಿ ಸಂಖ್ಯೆ ನಿಮ್ಮ ಕಾರ್ಡ್‌ನ ಹಿಂಭಾಗದಲ್ಲಿರುವ ಕೊನೆಯ ಮೂರು ಅಂಕೆಗಳು",
            btnOk: "ಸರಿ",
            cvvValidate: "ಅಮಾನ್ಯ ಸಿವಿವಿ",
            emptyCvv: "ದಯವಿಟ್ಟು ಸಿವಿವಿ ನಮೂದಿಸಿ",
            nameOnCard: "ಕಾರ್ಡ್‌ನಲ್ಲಿ ಹೆಸರು",
            nameError: "ದಯವಿಟ್ಟು ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
            invalidError: "ಅಮಾನ್ಯ ಹೆಸರು",
            saveCardCheckboxText: "ಭವಿಷ್ಯದ ಪಾವತಿಗಳಿಗಾಗಿ ಈ ಕಾರ್ಡ್ ಉಳಿಸಿ",
            otherBank: "ಇತರ ಬ್ಯಾಂಕ್",
            errorBankList: "ದಯವಿಟ್ಟು ಬ್ಯಾಂಕ್ ಆಯ್ಕೆಮಾಡಿ",
            vpaAddress: "ವರ್ಚುವಲ್ ಪಾವತಿ ವಿಳಾಸ",
            invalidVpa: "ಅಮಾನ್ಯ ವಿಪಿಎ",
            enterVpa: "ದಯವಿಟ್ಟು ವಿಪಿಎ ನಮೂದಿಸಿ",
            vpaPara: "ಯುಪಿಐ ಐಡಿ ಒಂದು ಅನನ್ಯ ಪಾವತಿ ವಿಳಾಸವಾಗಿದ್ದು, ಪಾವತಿಗಳನ್ನು ಮಾಡಲು ವ್ಯಕ್ತಿಯ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಲಿಂಕ್ ಮಾಡಲಾಗಿದೆ.",
            vpaName: "ಹೆಸರು",
            invalidVpaName: "ಅಮಾನ್ಯ ಹೆಸರು",
            enterVpaName: "ದಯವಿಟ್ಟು ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
            saveVpaText: "ಭವಿಷ್ಯದ ಪಾವತಿಗಳಿಗಾಗಿ ಈ ವಿಪಿಎ ಉಳಿಸಿ",
            poweredBy: "ನಡೆಸುವವರು:",
            errorWalletList: "ದಯವಿಟ್ಟು ಯಾವುದೇ ವ್ಯಾಲೆಟ್ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ",
            errorCOD: "ದಯವಿಟ್ಟು COD ಆಯ್ಕೆಮಾಡಿ",
            emiValue: "ಇಎಂಐ ಮೌಲ್ಯ",
            emiInterestText: "ಆಸಕ್ತಿ",
            chargedByBank: "(ಬ್ಯಾಂಕ್‌ನಿಂದ ವಿಧಿಸಲಾಗುತ್ತದೆ)",
            totalEmiText: "",
            emiMonthsText: "ತಿಂಗಳ ಒಟ್ಟು ಇಎಂಐ",
            cancel: "ರದ್ದುಮಾಡಿ",
            payBtnText: "ಪಾವತಿ",
            selectBank: "ಬ್ಯಾಂಕ್ ಆಯ್ಕೆಮಾಡಿ",
            selectDebitCredit: "ಡೆಬಿಟ್ / ಕ್ರೆಡಿಟ್ ಆಯ್ಕೆಮಾಡಿ",
            emiBankErrorBefore: "ದಯವಿಟ್ಟು ",
            emiBankErrorAfter: " ಕಾರ್ಡ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
            emiCardErrorBefore: "ದಯವಿಟ್ಟು ",
            emiCardErrorAfter: " ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
            errorCardDomestic: "ಡೊಮೆಸ್ಟಿಕ್ ಕಾರ್ಡ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
            emiFor: ",",
            emiMonths: "ತಿಂಗಳು",
            timeExpireTextBefore: "ಈ ಪುಟವು",
            timeExpireTextAfter: "ರಲ್ಲಿ ಮುಕ್ತಾಯಗೊಳ್ಳುತ್ತದೆ",
            retryHeading: "ಪಾವತಿ ವಿಫಲವಾಗಿದೆ? ಈಗ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
            retryBtn: "ಮರುಪ್ರಯತ್ನಿಸಿ",
            returnMerchant: "ವ್ಯಾಪಾರಿಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
            upiApprovalText: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಯುಪಿಐ ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ಪಾವತಿಯನ್ನು ಅನುಮೋದಿಸಿ",
            upiStopRefresh: "ಈ ಪುಟವನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಬೇಡಿ ಅಥವಾ ಬ್ಯಾಕ್ ಬಟನ್ ಒತ್ತಿರಿ",
            seeDetails: "ವಿವರಗಳನ್ನು ನೋಡಿರಿ",
            hideDetails: "ವಿವರಗಳನ್ನು ಮರೆಮಾಡಿ",
            defaultLoaderText: "ನಿಮ್ಮ ಪಾವತಿಯನ್ನು ನಾವು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವಾಗ ದಯವಿಟ್ಟು ಕಾಯಿರಿ...",
            summary: "ಸಾರಾಂಶ",
            quickPay: "ತ್ವರಿತ ವೇತನ",
            gst: "GST",
            mobileNumber: "ಮೊಬೈಲ್ ನಂಬರ",
            useAnotherMobile: "ಮತ್ತೊಂದು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಬಳಸಿ",
            enterOtp: "OTP ನಮೂದಿಸಿ",
            resendOtp: "OTP ಯನ್ನು ಮರುಹೊಂದಿಸಿ",
            availableBalance: "ಲಭ್ಯವಿರುವ ಬ್ಯಾಲೆನ್ಸ್",
            refreshBalance: "ಬ್ಯಾಲೆನ್ಸ್ ಪರಿಶೀಲಿಸಿ",
            addMoney: "ಹಣವನ್ನು ಸೇರಿಸಿ",
            insufficientFund: "ಸಾಕಷ್ಟು ಹಣವಿಲ್ಲ!",
            rechargeWallet: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ವ್ಯಾಲೆಟ್ ಅನ್ನು ರೀಚಾರ್ಜ್ ಮಾಡಿ ...",
            useAnotherMobileAlt: "ಮತ್ತೊಂದು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಬಳಸಿ ಲಾಗಿನ್ ಮಾಡಿ",
            loggedIn: "ನೀವು",
            loggedInAlt: "ಬಳಸಿ ಲಾಗ್ ಇನ್ ಆಗಿದ್ದೀರಿ",
            payUsingUpi: "ಯುಪಿಐ ಐಡಿ ಬಳಸುವುದನ್ನು ಪಾವತಿಸಿ",
            payUsingQr: "QR ಕೋಡ್ ಬಳಸಿ ಪಾವತಿಸಿ"
        },
        arabic: {
            upiQrText: "(يرجى مسح UPI QR ضوئيًا باستخدام أي تطبيق UPI)",
            saveWlText: "احفظ هذه المحفظة للمدفوعات المستقبلية",
            saveNbText: "احفظ هذا البنك للدفعات المستقبلية",
            expiry: "انقضاء",
            orderId: "معرف الطلب",
            amount: "كمية",
            convenienceFee: "رسوم الراحة",
            amountPayable: "المبلغ المستحق",
            savedCards: "البطاقات المحفوظة",
            savedVpa: "VPA تم حفظ",
            savedBanks: "البنوك المحفوظة",
            savedWallet: "المحافظ المحفوظة",
            card: "البطاقات",
            creditCard: "بطاقة الائتمان",
            debitCard: "بطاقة ائتمان",
            international: "عالمي",
            upi: "واجهة دفع موحدة",
            upiQr: "امسح وادفع",
            netBanking: "صافي الخدمات المصرفية",
            wallet: "محفظة نقود",
            paytm: "پے ٹی ایم",
            cashondelivery: "الدفع عند الاستلام",
            payathotel: "ادفع في الفندق",
            payondelivery: "الدفع عند الاستلام",
            emi: "القسط الشهري المعادل",
            cardNumber: "رقم البطاقة",
            checkStartNo: "رقم البطاقة غير صالحة",
            validCardCheck: "رقم البطاقة غير صالحة",
            emptyCardNumber: "الرجاء إدخال رقم البطاقة",
            notSupportedCard: "البطاقة غير مدعومة",
            validExpDate: "تاريخ غير صالح",
            emptyExpiry: "أدخل تاريخ الانتهاء",
            cvvTitle: "ما هي CVV؟",
            cvvText: "رقم CVV هو آخر ثلاثة أرقام على ظهر بطاقتك",
            btnOk: "حسنا",
            cvvValidate: "CVV غير صالح",
            emptyCvv: "يرجى إدخال CVV",
            nameOnCard: "الاسم على البطاقة",
            nameError: "من فضلك ادخل الاسم",
            invalidError: "الاسم غير صالح",
            saveCardCheckboxText: "حفظ هذه البطاقة للدفعات المستقبلية",
            otherBank: "بنك آخر",
            errorBankList: "يرجى تحديد البنك",
            vpaAddress: "عنوان الدفع الافتراضي",
            invalidVpa: "VPA غير صالح",
            enterVpa: "الرجاء إدخال VPA",
            vpaPara: "UPI ID هو عنوان دفع فريد مرتبط بالحساب المصرفي للشخص لإجراء الدفعات.",
            vpaName: "اسم",
            invalidVpaName: "الاسم غير صالح",
            enterVpaName: "من فضلك ادخل الاسم",
            saveVpaText: "حفظ هذا VPA للدفعات المستقبلية",
            poweredBy: "مشغل بواسطة:",
            errorWalletList: "الرجاء اختيار أي نوع من المحفظة",
            errorCOD: "الرجاء اختيار COD",
            emiValue: "قيمة EMI",
            emiInterestText: "فائدة",
            chargedByBank: "(يتقاضاها البنك)",
            totalEmiText: "أشهر",
            emiMonthsText: "لمدة EMI مجموع",
            cancel: "إلغاء",
            payBtnText: "دفع",
            selectBank: "حدد البنك",
            selectDebitCredit: "حدد الخصم / الائتمان",
            emiBankErrorBefore: "رقم البطاقة ",
            emiBankErrorAfter: " الرجاء إدخال",
            emiCardErrorBefore: "",
            emiCardErrorAfter: " يرجى إدخال رقم",
            errorCardDomestic: "الرجاء إدخال رقم البطاقة المحلية",
            emiFor: "اشهر",
            emiMonths: "لمدة",
            timeExpireTextBefore: "",
            timeExpireTextAfter: "هذه الصفحة ستنتهي في",
            retryHeading: "عملية الدفع فشلت؟ أعد المحاولة الآن",
            retryBtn: "أعد المحاولة",
            returnMerchant: "ارجع إلى التاجر",
            upiApprovalText: "يرجى الموافقة على الدفع في تطبيق UPI الخاص بك",
            upiStopRefresh: "لا تقم بتحديث هذه الصفحة أو الضغط على زر العودة",
            seeDetails: "انظر التفاصيل",
            hideDetails: "أخف التفاصيل",
            defaultLoaderText: "يرجى الانتظار بينما نقوم بمعالجة الدفع الخاص بك",
            summary: "ملخص",
            quickPay: "الدفع السريع",
            gst: "GST",
            mobileNumber: "رقم الهاتف المحمول",
            useAnotherMobile: "استخدم رقم هاتف محمول آخر",
            enterOtp: "أدخل OTP",
            resendOtp: "إعادة إرسال OTP",
            availableBalance: "الرصيد المتوفر",
            refreshBalance: "تحقق من الرصيد",
            addMoney: "إضافة المال",
            insufficientFund: "رصيد غير كاف!",
            rechargeWallet: "الرجاء إعادة شحن محفظتك ...",
            useAnotherMobileAlt: "تسجيل الدخول باستخدام رقم موبايل آخر",
            loggedIn: "",
            loggedInAlt: "لقد قمت بتسجيل الدخول باستخدام ",
            payUsingUpi: "UPI ادفع باستخدام معرف",
            payUsingQr: "ادفع باستخدام رمز الاستجابة السريعة"
        },
    };

    return $multilingualText[lang][dataKey];
}