package com.paymentgateway.commons.util;

/**
 * @author Amitosh Aanand
 *
 */
public enum ElectricityBoardType {

	APSPDCL ("ANDHRA PRADESH" , "SOUTHERN POWER DISTRIBUTION COMPANY OF ANDHRA PRADESH LIMITED" , "APSPDCL"),
	APEPDCL ("ANDHRA PRADESH"	, "EASTERN POWER DISTRIBUTION COMPANY OF ANDHRA PRADESH LIMITED" , "APEPDCL"),
	CH_ELEC ("CHANDIGARH" , "CHANDIGARH ELECTRICITY DEPARTMENT" , "CH_ELEC"),
	CSPDCL ("CHHATTISGARH" , "CHHATTISGARH STATE POWER DISTRIBUTION COMPANY LIMITED" , "CSPDCL"),
	DAMAN_DIU ("DAMAN & DIU" , "DAMAN AND DIU ELECTRICITY DEPARTMENT" , "DAMAN_DIU"),
	TATA_DL ("DELHI" , "TATA POWER DELHI DISTRIBUTION" , "TATA_DL"),
	BSES_DL ("DELHI" , "BSES YAMUNA POWER LTD / BSES RAJDHANI POWER LTD" , "BSES_DL"),
	GOA_ELEC ("GOA" , "GOA ELECTRICITY- FOR TISVADI, PONDA & VERNA" , "GOA_ELEC"),
	UPAY_GOA ("GOA" , "GOA ELECTRICITY- FOR OTHERS" , "UPAY_GOA"),
	UGVCL ("GUJARAT" , "UTTAR GUJARAT VIJ COMPANY LTD." , "UGVCL"),
	PGVCL ("GUJARAT" , "PASHCHIM GUJARAT VIJ COMPANY LTD." , "PGVCL"),
	MGVCL ("GUJARAT" , "MADHYA GUJARAT VIJ COMPANY LIMITED" , "MGVCL"),
	DGVCL ("GUJARAT" , "DAKSHIN GUJARAT VIJ COMPANY LIMITED" , "DGVCL"),
	DHBVN ("HARYANA" , "DAKSHIN HARYANA BIJLI VITRAN NIGAM" , "DHBVN"),
	UHBVN ("HARYANA" , "UTTAR HARYANA BIJLI VITRAN NIGAM" , "UHBVN"),
	HPSEB ("HIMACHAL PRADESH" , "HIMACHAL PRADESH STATE ELECTRICITY BOARD LTD" , "HPSEB"),
	MESCOM ("KARNATAKA" , "MANGALORE ELECTRICITY SUPPLY COMPANY LIMITED" , "MESCOM"),
	BESCOM ("KARNATAKA" , "BANGALORE ELECTRICITY SUPPLY COMPANY LTD" , "BESCOM"),
	CESCOM ("KARNATAKA" , "CHAMUNDESHWARI ELECTRICITY SUPPLY COMPANY LIMITED MYSORE" , "CESCOM"),
	GESCOM ("KARNATAKA" , "GULBARGA ELECTRICITY SUPPLY COMPANY LIMITED" , "GESCOM"),
	HESCOM ("KARNATAKA" , "HUBLI ELECTRICITY SUPPLY COMPANY LIMITED" , "HESCOM"),
	MPWZ ("MADHYA PRADESH" , "MADHYA PRADESH PASCHIM KSHETRA VIDYUT VITRAN COMPANY LIMITED" , "MPWZ"),
	MPCZ ("MADHYA PRADESH" , "MADHYA PRADESH MADHYA KSHETRA VIDYUT VITRAN COMPANY LIMITED" , "MPCZ"),
	MPEZ ("MADHYA PRADESH" , "MADHYA PRADESH POORV KSHETRA VIDYUT VITRAN COMPANY LIMITED" , "MPEZ"),
	TATA_MUMBAI ("MAHARASHTRA" , "TATA-POWER - MUMBAI" , "TATA_MUMBAI"),
	BEST ("MAHARASHTRA" , "BEST UNDERTAKING" , "BEST"),
	MAHAVITRAN ("MAHARASHTRA" , "MAHAVITARAN-MAHARASHTRA STATE ELECTRICITY DISTRIBUTION CO. LTD (MSEDCL)" , "MAHAVITRAN"),
	RELIANCE_MH ("MAHARASHTRA" , "RELIANCE ENERGY - MUMBAI" , "RELIANCE_MH"),
	ORISSA ("ORISSA" , "SUPPLY COMPANY OF ORISSA LIMITED (NORTH, SOUTH & WEST)" , "ORISSA"),
	PSPCL ("PUNJAB" , "PUNJAB STATE POWER CORPORATION LIMITED" , "PSPCL"),
	JAIPUR ("RAJASTHAN" , "JAIPUR VIDHYUT VITRAN NIGAM LTD" , "JAIPUR"),
	AJMER ("RAJASTHAN" , "AJMER VIDHYUT VITRAN NIGAM LTD" , "AJMER"),
	JODHPUR ("RAJASTHAN" , "JODHPUR VIDHYUT VITRAN NIGAM LTD" , "JODHPUR"),
	KESCO ("UTTAR PRADESH" , "KANPUR ELECTRICITY SUPPLY COMPANY" , "KESCO"),
	UPPCL ("UTTAR PRADESH" , "UP VIDYUT VITRAN NIGAM LIMITED (ALL ZONES)" , "UPPCL"),
	TORRENT_AHD ("GUJARAT" , "TORRENT POWER LIMITED - AHMEDABAD" , "TORRENT_AHD"),
	TORRENT_SURAT ("GUJARAT" , "TORRENT POWER LIMITED - SURAT" , "TORRENT_SURAT"),
	TORRENT_AGRA ("GUJARAT" , "TORRENT POWER LIMITED - AGRA" , "TORRENT_AGRA"),
	TORRENT_BHIWANDI ("GUJARAT" , "TORRENT POWER LIMITED - BHIWANDI" , "TORRENT_BHIWANDI"),
	TORRENT_DAHEJ ("GUJARAT" , "TORRENT POWER LIMITED - DAHEJ" , "TORRENT_DAHEJ"),
	NBPDCL ("BIHAR" , "NORTH BIHAR POWER DISTRIBUTION COMPANY LIMITED" , "NBPDCL"),
	SBPDCL ("BIHAR" , "SOUTH BIHAR POWER DISTRIBUTION COMPANY LIMITED" , "SBPDCL"),
	TSSPCL ("TELANGANA" , "THE SOUTHERN POWER DISTRIBUTION COMPANY OF TELANGANA LIMITED" , "TSSPCL"),
	APDCL ("ASSAM" , "ASSAM POWER DISTRIBUTION COMPANY LIMITED" , "APDCL"),
	CHENNAI_NORTH ("TAMIL NADU" , "TAMIL NADU GENERATION AND DISTRIBUTION CORPORATION LIMITED - CHENNAI_NORTH" , "CHENNAI_NORTH"),
	VILLUPURAM ("TAMIL NADU" , "TAMIL NADU GENERATION AND DISTRIBUTION CORPORATION LIMITED - VILLUPURAM" , "VILLUPURAM"),
	COIMBATORE ("TAMIL NADU" , "TAMIL NADU GENERATION AND DISTRIBUTION CORPORATION LIMITED - COIMBATORE" , "COIMBATORE"),
	ERODE ("TAMIL NADU" , "TAMIL NADU GENERATION AND DISTRIBUTION CORPORATION LIMITED - ERODE" , "ERODE"),
	MADURAI ("TAMIL NADU" , "TAMIL NADU GENERATION AND DISTRIBUTION CORPORATION LIMITED - MADURAI" , "MADURAI"),
	TRICHY ("TAMIL NADU" , "TAMIL NADU GENERATION AND DISTRIBUTION CORPORATION LIMITED - TRICHY" , "TRICHY"),
	TIRUNELVEL ("TAMIL NADU" , "TAMIL NADU GENERATION AND DISTRIBUTION CORPORATION LIMITED - TIRUNELVEL" , "TIRUNELVEL"),
	VELLORE ("TAMIL NADU" , "TAMIL NADU GENERATION AND DISTRIBUTION CORPORATION LIMITED - VELLORE" , "VELLORE"),
	CHENNAI_SOUTH ("TAMIL NADU" , "TAMIL NADU GENERATION AND DISTRIBUTION CORPORATION LIMITED - CHENNAI_SOUTH" , "CHENNAI_SOUTH");
	
	private final String state;
	private final String name;
	private final String code;

	private ElectricityBoardType(String state, String name, String code) {
		this.code = code;
		this.name = name;
		this.state = state;
	}

	public String getCode() {
		return code;
	}

	public String getName() {
		return name;
	}

	public String getState() {
		return state;
	}

	public static ElectricityBoardType getInstancefromCode(String boardCode) {
		ElectricityBoardType electricityBoardType = null;
		for (ElectricityBoardType board : ElectricityBoardType.values()) {
			if (boardCode.equals(board.getCode().toString())) {
				electricityBoardType = board;
				break;
			}
		}
		return electricityBoardType;
	}
	
	public static ElectricityBoardType getInstancefromName(String boardName) {
		ElectricityBoardType electricityBoardType = null;
		for (ElectricityBoardType board : ElectricityBoardType.values()) {
			if (boardName.equals(board.getName())) {
				electricityBoardType = board;
				break;
			}
		}
		return electricityBoardType;
	}

	public static String getElectricityBoardName(String boardCode) {
		String electricityBoardType = null;
		if (null != boardCode) {
			for (ElectricityBoardType board : ElectricityBoardType.values()) {
				if (boardCode.equals(board.getCode().toString())) {
					electricityBoardType = board.getName();
					break;
				}
			}
		}
		return electricityBoardType;
	}
	
	public static String getElectricityBoardCode(String boardName) {
		String electricityBoardCode = null;
		if (null != boardName) {
			for (ElectricityBoardType board : ElectricityBoardType.values()) {
				if (boardName.equals(board.getName().toString())) {
					electricityBoardCode = board.getCode();
					break;
				}
			}
		}
		return electricityBoardCode;
	}
}
